version: '3'
services:
    db:
      ports:
      - "5432:5432"
      volumes:
        - ./fixtures:/fixtures
      container_name: eventzimmer_schema-db
    api:
      ports:
      - "3000:3000"
    docs:
      environment:
        URL: http://localhost:3000
      ports:
      - "8080:8080"
