version: '3'
services:
  proxy:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ~/.data/traefik:/etc/traefik/acme/
    networks:
      - web
  db:
    restart: always
    volumes:
      - ~/.data/postgres:/var/lib/postgresql/data
    networks:
      - internal
  api:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:api.eventzimmer.de"
      - "traefik.port=3000"
    networks:
      - internal
      - web
    environment:
      PGRST_JWT_SECRET: "{\"alg\":\"RS256\",\"kty\":\"RSA\",\"use\":\"sig\",\"n\":\"qcmjboEq-H8UuGlGtjewi83HZyXJ_-1wdmw-QyoHmtabo1ZNn0cH78VYlHcxvAj5BobrHa2Ed6Uyb3r0Y4Vh6NOVtks3-IWGWfTiJAtb5PXKyQLESTJCJgPnNUerYLTU-viEQXnYGz1LmPb3KqFJrUp8FEvqH6FBrHqaVGTa8tvJA5lN6yOURv6z-NALxO5Lko_xBHku33syOUu52wPupK-QKlPdUzh8NRIOLny8RVumUs_GXm76lKiBCH3QNxzSRCJb4b5JF-vr5CIAW-S9nUM6u4cBnNMci7FSxP5GS1mx0Z4InUFDhOlWShxCGnr0dN5RHNL3i6pK3JLJmWWU9Q\",\"kid\":\"RTEyMDNCQUJDMUFGNUQyQ0YwRTk2M0Q0OTFGNDdBMDU4RTlERUM2MA\",\"e\":\"AQAB\"}"
      PGRST_SERVER_PROXY_URI: "https://api.eventzimmer.de:443"

networks:
  internal:
  web:
    external: true
